#!/usr/bin/env bash

STATS_FILE=~/.ninja-stats/stats
if [ ! -e $STATS_FILE ]; then
	mkdir -p ~/.ninja-stats
	touch $STATS_FILE
fi

start=$(date +%s)

LOG_FILE=$(mktemp)

echo "[INFO] Writing statistics to $STATS_FILE"
ninja-build $@ | tee $LOG_FILE

end=$(date +%s)
duration=$((end - start))
cxx_count=$(grep "\] CXX" $LOG_FILE | wc -l)
error=$(grep "subcommand failed" $LOG_FILE | wc -l)
echo "[INFO] Compiled $cxx_count files in $duration seconds (error=${error})"
echo "${start},${duration},${error},${cxx_count},$(date +%Y-%m-%d:%H:%M:%S),$(pwd)" >> $STATS_FILE

rm $LOG_FILE
exit $code
