#!/usr/bin/env bash

STATS_FILE=~/.ninja-stats/stats
if [ ! -e $STATS_FILE ]; then
	echo "[INFO] Creating statistics file in $STATS_FILE"
	mkdir -p ~/.ninja-stats
	touch $STATS_FILE
fi

LOG_FILE=$(mktemp)
echo "[INFO] Logging to $LOG_FILE"

start=$(date +%s)

ninja-build $@ | tee $LOG_FILE
code=$?

end=$(date +%s)
duration=$((end - start))
cxx_count=$(grep "\] CXX" $LOG_FILE | wc -l)

echo "[INFO] Compiled $cxx_count files in $duration seconds (exit code ${code})"
echo "${start},${duration},${code},${cxx_count},$(date +%Y-%m-%d:%H:%M:%S)" >> $STATS_FILE

rm $LOG_FILE
exit $code
